"""test

Revision ID: 0714d7b808da
Revises: ad042e3bf92a
Create Date: 2017-10-12 23:08:57.751000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0714d7b808da'
down_revision = 'ad042e3bf92a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
