"""add connect_mail

Revision ID: c9007e2a2a58
Revises: b2facb003790
Create Date: 2017-10-17 17:24:00.539000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9007e2a2a58'
down_revision = 'b2facb003790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('connect_mail', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'connect_mail')
    # ### end Alembic commands ###
